# -*- coding: utf-8 -*-
"""3_minorcb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ce9u_IT0CoI1CQaGKKQVZMJ4FmVGxZsn
"""

!ls /content/drive/MyDrive/3Yolo_Custom_Object_Detection

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/3Yolo_Custom_Object_Detection/darknet

# !git clone 'https://github.com/AlexeyAB/darknet.git' '/content/drive/MyDrive/3Yolo_Custom_Object_Detection/darknet'

!ls

!make clean

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/3Yolo_Custom_Object_Detection

!python custom_data/creating-files-data-and-name.py

!python custom_data/creating-train-and-test-txt-files.py

# !darknet/darknet detector train custom_data/labelled_data.data /content/drive/MyDrive/3Yolo_Custom_Object_Detection/darknet/cfg/yolov3_custom.cfg custom_weight/darknet53.conv.74 -dont_show

!darknet/darknet



