# -*- coding: utf-8 -*-
"""5atten.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i2uo3A_V8jg8UIlPbMZOG_cqcrMavMkd
"""

!ls /content/drive/MyDrive/5Yolo_Custom_Object_Detection

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/5Yolo_Custom_Object_Detection/darknet

!ls

!make clean

!make

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/5Yolo_Custom_Object_Detection

!python custom_data/creating-files-data-and-name.py

!python custom_data/creating-train-and-test-txt-files.py

!darknet/darknet detector train custom_data/labelled_data.data darknet/cfg/yolov3_custom.cfg backup/yolov3_custom_last.weights -dont_show



